jms_serializer:
    metadata:
        directories:
            SwitchUser:
                namespace_prefix: "KimaiPlugin\\SwitchUserBundle"
                path: "@SwitchUserBundle/Resources/config/serializer"
        # warmup:
        #     paths:
        #         included:
        #             - "%kernel.root_dir%/../var/plugins/SwitchUserBundle/Entity/"
